import { Inter } from "next/font/google";
import "../style/globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Countries app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="dark" lang="en">
      <body className={`${inter.className} dark:bg-darkBlue `}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
